## 1. Indexing

In [1]:
import numpy as np

In [37]:
## 기본 활용은 Python 인덱스와 동일

# 1) 1차원
x = np.arange(1,10)
print("1차원 행렬", x)
print("1차원 원소 추출 x[0] :", x[0], "\n")

# 2) 2차원
y = np.arange(10).reshape(2, 5)
print("2차원 행렬\n", y)
print("2차원 원소 추출 y[1.3] :", y[1,3], "\n") # 하나의 원소를 추출하기위해 행과 열 수를 기재

# 3) 3차원
z = np.arange(36).reshape(3, 4, 3)
print("3차원 행렬\n",z)
print("3차원 원소 추출 z[1,2,1] :", z[1,2,1])

1차원 행렬 [1 2 3 4 5 6 7 8 9]
1차원 원소 추출 x[0] : 1 

2차원 행렬
 [[0 1 2 3 4]
 [5 6 7 8 9]]
2차원 원소 추출 y[1.3] : 8 

3차원 행렬
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]
3차원 원소 추출 z[1,2,1] : 19


## 2. Slicing

In [41]:
# 1) 1차원
x = np.arange(1,10)
print(x)
x[1:7]

[1 2 3 4 5 6 7 8 9]


array([2, 3, 4, 5, 6, 7])

In [63]:
# 2) 2차원
y = np.arange(10).reshape(2, 5)
print("원래의 값\n", y ,"\n")

# 둘의 차이점 알아놓자

print(y[1: , 0:3]) # Slicing (슬라이싱은 차원을 유지하면서 자르는 것)

print(y[0 , 0:3]) # Indexing + Slicing

원래의 값
 [[0 1 2 3 4]
 [5 6 7 8 9]] 

[[5 6 7]]
[0 1 2]


In [82]:
# 3) 3차원

z = np.arange(36).reshape(3, 4, 3)
print("원래의 값\n",z ,"\n")

# 17의 값을 가져와보자
z[1:2, 1:2, 2:]

원래의 값
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]] 



array([[[17]]])

## 3. 데이터 형태 변환 (reshape, flatten)

#### ravel, np.ravel
* 다차원 배열 -> 1차원으로 변경

#### flatten
* 다차원 배열 -> 1차원으로 변경한 **복사본**을 반환

#### 정렬
* order 파라미터를 사용
    * C : row 우선 변경
    * F : Col 우선 변경

In [21]:
## 1) ravel 사용
x = np.arange(15).reshape(3,5)
print(x)

np.ravel(x, order='F')

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


array([ 0,  5, 10,  1,  6, 11,  2,  7, 12,  3,  8, 13,  4,  9, 14])

In [22]:
## 2) flatten 사용
y = np.arange(15).reshape(3,5)
y.flatten(order='F')

array([ 0,  5, 10,  1,  6, 11,  2,  7, 12,  3,  8, 13,  4,  9, 14])

In [15]:
####################################################
## ravel과 faltten의 차이
#####################################################

# 둘다 Temp 변수로 넣음
temp_1 = x.ravel()
temp_2 = y.flatten()

# temp 변수의 첫번째 값을 100으로 변경함
temp_1[0] = 100
temp_2[0] = 100

# 이때 x와 y의 값에 대한 변화 출력
# temp를 변경하면 x도 함께 값이 변하나, y는 변하지 않는다
print("x의 값", x)
print("y의 값", y)

x의 값 [[100   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]]
y의 값 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [24]:
## 3차원 배열 변환 하기
z = np.arange(30).reshape(2,3,5)
print(z)

z.ravel()

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

#### reshape 함수
* **reshape한 후의 전체 원소 개수**와 **변환 전 개수**가 같아야 함
* [사용 예시] 이미지 데이터 벡터화 등
    * 이미지는 기본적으로 2차원 혹은 3차원(RGB)이지만 트레이닝을 위해 1차원으로 변경하여 사용

In [30]:
x = np.arange(32)
print(x)

x.reshape(8,4)

# 아래와 같이 -1를 사용할 경우, 이미 2와 4를 썼기때문에
# 남은 값이 4임을 유추할수 있어서 사용 가능 (빈번히 사용함)
y = x.reshape(2, 4, -1)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]]
