## 1. Indexing

In [ ]:
import numpy as np

In [37]:
## 기본 활용은 Python 인덱스와 동일

# 1) 1차원
x = np.arange(1,10)
print("1차원 행렬", x)
print("1차원 원소 추출 x[0] :", x[0], "\n")

# 2) 2차원
y = np.arange(10).reshape(2, 5)
print("2차원 행렬\n", y)
print("2차원 원소 추출 y[1.3] :", y[1,3], "\n") # 하나의 원소를 추출하기위해 행과 열 수를 기재

# 3) 3차원
z = np.arange(36).reshape(3, 4, 3)
print("3차원 행렬\n",z)
print("3차원 원소 추출 z[1,2,1] :", z[1,2,1])

1차원 행렬 [1 2 3 4 5 6 7 8 9]
1차원 원소 추출 x[0] : 1 

2차원 행렬
 [[0 1 2 3 4]
 [5 6 7 8 9]]
2차원 원소 추출 y[1.3] : 8 

3차원 행렬
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]
3차원 원소 추출 z[1,2,1] : 19


## 2. Slicing

In [41]:
# 1) 1차원
x = np.arange(1,10)
print(x)
x[1:7]

[1 2 3 4 5 6 7 8 9]


array([2, 3, 4, 5, 6, 7])

In [63]:
# 2) 2차원
y = np.arange(10).reshape(2, 5)
print("원래의 값\n", y ,"\n")

# 둘의 차이점 알아놓자

print(y[1: , 0:3]) # Slicing (슬라이싱은 차원을 유지하면서 자르는 것)

print(y[0 , 0:3]) # Indexing + Slicing

원래의 값
 [[0 1 2 3 4]
 [5 6 7 8 9]] 

[[5 6 7]]
[0 1 2]


In [82]:
# 3) 3차원

z = np.arange(36).reshape(3, 4, 3)
print("원래의 값\n",z ,"\n")

# 17의 값을 가져와보자
z[1:2, 1:2, 2:]

원래의 값
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]] 



array([[[17]]])