In [1]:
import numpy as np

## 1. broadcasting
* 연산되는 두 ndarry가 다른 Shape을 갖는 경우 브로드 캐스팅(Shape를 맞춤) 후 진행

In [2]:
x = np.arange(15).reshape(3,5)
y = np.random.rand(15).reshape(3,5)

In [3]:
## Shape이 같은 경우 연산
x + y

## 상수 연산
x * 2

array([[ 0.02786926,  1.58664545,  2.49470056,  3.80230195,  4.1692084 ],
       [ 5.30512394,  6.40694144,  7.29438133,  8.85247368,  9.05284003],
       [10.36363715, 11.85079961, 12.42090621, 13.38560928, 14.86674871]])

#### shape이 다른 경우 연산

In [15]:
a = np.arange(12).reshape(4,3)
b = np.arange(100, 103)
c = np.arange(1000, 1004)
d = b.reshape(1,3)

print(a)
print(b)
print(c)
print(d)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[100 101 102]
[1000 1001 1002 1003]
[[100 101 102]]


In [16]:
print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)

(4, 3)
(3,)
(4,)
(1, 3)


In [18]:
a + b
a + d

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])

## 2. Boolean Indexing
* ndarry 인덱싱 시, bool 리스트를 전달하여 True인 경우만 필터링

In [19]:
x = np.random.randint(1,100, size=10)
print(x)

[89 39 43  7 54 66  6 87  2 24]


In [24]:
# 아래 2값이 스칼라 상수임으로 브로드캐스팅 발생
# 따라서 2로 나눈 값이 0인지 아닌지 True,False로 반환 (boolean List)
even_mask = x % 2 == 0
print(even_mask)

[False False False False  True  True  True False  True  True]


In [23]:
# bool 리스트를 인덱스로 전달
x[even_mask]

# 위 내용은 보통 아래와 같이 한번에 사용
x [x % 2 == 0]

array([54, 66,  6,  2, 24])

In [25]:
x [x > 30]

array([89, 39, 43, 54, 66, 87])

#### 다중 조건 사용하기

In [31]:
x[ (x % 2 == 0) & (x > 30) ]

x[ ( x < 50 ) | (x > 30) ]

array([89, 39, 43,  7, 54, 66,  6, 87,  2, 24])

#### 예제) 19년 7월 서울 평균 기온 데이터
* 평균 기온이 25도를 넘는 일수
* 평균 기온이 25도를 넘는 날의 평균 기온

In [32]:
temp = np.array(
        [23.9, 24.4, 24.1, 25.4, 27.6, 29.7,
         26.7, 25.1, 25.0, 22.7, 21.9, 23.6, 
         24.9, 25.9, 23.8, 24.7, 25.6, 26.9, 
         28.6, 28.0, 25.1, 26.7, 28.1, 26.5, 
         26.3, 25.9, 28.4, 26.1, 27.5, 28.1, 25.8])

In [48]:
sum(temp > 25.0)

np.mean(temp [temp > 25.0])

26.857142857142858