In [3]:
import numpy as np

## 1. 기본 함수

> 연산
* add, substract, multiply 등

> 통계
* mean, var, median, sid 등 

> 집계
* sum, cumsum 등

> 조건식
* any, all, where

#### numpy doc
- [numpy 공식 문서 링크](https://www.numpy.org/devdocs/reference/)

In [5]:
x = np.arange(20).reshape(4,5)
y = np.random.rand(20).reshape(4,5)

print(x)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[0.49657451 0.88647648 0.4233526  0.44661184 0.04895956]
 [0.66717913 0.25333338 0.33135849 0.07908459 0.54966903]
 [0.18594897 0.39693487 0.85883131 0.25622451 0.04717227]
 [0.8789637  0.59336817 0.08016928 0.17318945 0.70180066]]


#### 연산 함수
* add, substract, multiply, divide

In [9]:
# 함수 사용
np.add(x,y)

## 연산자로 사용하여 가능 !!
x - y

array([[-0.49657451,  0.11352352,  1.5766474 ,  2.55338816,  3.95104044],
       [ 4.33282087,  5.74666662,  6.66864151,  7.92091541,  8.45033097],
       [ 9.81405103, 10.60306513, 11.14116869, 12.74377549, 13.95282773],
       [14.1210363 , 15.40663183, 16.91983072, 17.82681055, 18.29819934]])

#### 통계 함수
* mean, var, median, max, min 등 기초통계 관련 함수

In [14]:
print(y.mean())
print(y.max())

## 가장 큰 값의 index 추출
np.argmax(x)

0.4177601401082063
0.8864764790081607


19

#### 집계 함수
* sum, cumsum(누적합계) 등

In [22]:
np.sum(y)
np.cumsum(x) # 누적 합계임으로 누적 그래프 그리는 등 유용

# sum에서도 누적 합계 가능 (axios 파라미터를 사용)
print(x)

print(np.sum(x, 1)) # 행
print(np.sum(x, 0)) # 열

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[30 34 38 42 46]
[10 35 60 85]


#### any, all 함수
* any : 특정 조건을 만족하는 것이 하나라도 있으면 True, 아니면 False (or)
* all : 모든 원소가 특정 조건 만족 시 True, 아니면 False (and)

In [28]:
z = np.random.randn(10)
print(z)

[-1.1103849   0.22583505  0.35680324  0.92181149  0.77346944 -0.1433117
  0.06195795  0.03936693  0.74515668  1.04902946]


In [34]:
z > 0

array([False,  True,  True,  True,  True, False,  True,  True,  True,
        True])

In [32]:
np.any(z>0)

True

In [31]:
np.all(z != 0)

True

#### where 함수
* 빈번히 사용되는 함수 중 하나
* If문과 동일 기능이라고 생각하면 됨

In [36]:
z = np.random.randn(14)
print(z)

[ 0.37220684  0.75790423 -0.0596916  -1.04730281 -0.57261404 -0.42373611
  0.18109225  1.8258141  -1.75702194 -1.09638365  0.14611031  0.00618433
 -1.46603544  1.17591239]


In [38]:
# if문과 비슷한 느낌
# (조건, true, false) 형식으로 사용
np.where(z > 0, z, "0보다 작음")

array(['0.3722068378519641', '0.7579042339340334', '0보다 작음', '0보다 작음',
       '0보다 작음', '0보다 작음', '0.18109224989422035', '1.8258141044303422',
       '0보다 작음', '0보다 작음', '0.14611030792384572', '0.006184328583506296',
       '0보다 작음', '1.1759123888859297'], dtype='<U32')

## 2. axis 정의 및 함수 내 파라미터 활용
* axios는 기본적으로 **아래 차원별 0,1,2....n 값**을 가진다
* ex. x.reshape(3,5, 4)
*     axios 값 최대 : axios=2

In [43]:
x = np.arange(15)
print(x)

np.sum(x, axis=0)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


105

In [48]:
y = x.reshape(3,5)
print(y)

np.sum(y, 0)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


array([15, 18, 21, 24, 27])

In [58]:
z = np.arange(36).reshape(3,4,3)
print(z, "\n")

print("axis 0은 각 원소별 매핑\n", np.sum(z, 0), "\n")
print("axis 1은 열 방향으로 순차 진행\n", np.sum(z, 1), "\n")
print("axis 2은 행 방향으로 순차 진행\n", np.sum(z, 2), "\n")

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]] 

axis 0은 각 원소별 매핑
 [[36 39 42]
 [45 48 51]
 [54 57 60]
 [63 66 69]] 

axis 1은 열 방향으로 순차 진행
 [[ 18  22  26]
 [ 66  70  74]
 [114 118 122]] 

axis 2은 행 방향으로 순차 진행
 [[  3  12  21  30]
 [ 39  48  57  66]
 [ 75  84  93 102]] 



#### axis 값이 Tuple인 경우
* 해당 Tuple에 명시된 모든 axis에 대해 연산 수행

In [65]:
print(z)

np.sum(z, (0,2))

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]


array([117, 144, 171, 198])