In [1]:
import numpy as np

#### 개요) 선형대수 개념 다지기
[선형대수가 머신러닝에서 중요한 이유 : 기초개념 쉽게 적어놓음](https://medium.com/@serithemage/%EC%84%A0%ED%98%95%EB%8C%80%EC%88%98%EA%B0%80-%EC%99%9C-%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D%EC%97%90-%EC%9E%88%EC%96%B4%EC%84%9C-%EA%B0%80%EC%9E%A5-%EC%A4%91%EC%9A%94%ED%95%9C-%EC%88%98%ED%95%99%EC%9D%B8%EA%B0%80-9f793f82892e).

## linalg Module을 활용한 선형대수 연산

* np.linalg.inv
    * 역행렬을 구할때 사용
    * 모든 차원의 값이 같아야 연산 가능

In [6]:
x = np.random.rand(3,3)
print(x)

# 행렬끼리의 곱
# @ 기호 또는 numpy의 matmul 사용

# 역행렬 구하기
print(x @ np.linalg.inv(x))
print(np.matmul(x, np.linalg.inv(x)))

[[0.20318206 0.52507939 0.4421748 ]
 [0.3270034  0.98077351 0.7834992 ]
 [0.45073034 0.62542594 0.55005905]]
[[ 1.00000000e+00 -2.62416332e-16  3.17506102e-16]
 [-3.03416481e-15  1.00000000e+00  1.81955921e-16]
 [ 2.30010104e-15  3.75437434e-16  1.00000000e+00]]
[[ 1.00000000e+00 -2.62416332e-16  3.17506102e-16]
 [-3.03416481e-15  1.00000000e+00  1.81955921e-16]
 [ 2.30010104e-15  3.75437434e-16  1.00000000e+00]]


#### nplinalg.solve
* **Ax = B 형태**의 **선형대수식 솔루션** 제공


* 예제) 호랑이와 홍합의 합 : 25 / 호랑이 다리 + 홍합 다리 합 : 64
    * x + y 25
    * 2x + 4y = 64
    
    -> 이때 호랑이와 홍합의 수는?
    
    
* 풀이방식) 위의 식을 다음과 같이 풀이할 수 있다.

$$\begin{pmatrix} 1 & 1 \\ 2 & 4 \end{pmatrix}\begin{pmatrix} x \\ y \end{pmatrix}= \begin{pmatrix} 25 \\ 64 \end{pmatrix}$$

In [16]:
# 주어진 식
A = np.array([[1,1], [2,4]])

# 결과 값
B = np.array([25, 64])

# solve를 이용하여 호랑이와 홍합의 수를 알아냄!
x = np.linalg.solve(A, B)
print(x)

np.allclose(A@x, B)

[18.  7.]


True